name: generate-tag

on:
  workflow_dispatch:
    if: github.ref == 'refs/heads/main'
    inputs:
      stage:
        description: 'Stage'
        required: true
        default: 'auto'
        type: choice
        options:
          - 'alpha'
          - 'beta'
          - 'rc'
          - 'final'
          - 'auto'
      scope:
        description: 'Scope'
        required: true
        default: 'auto'
        type: choice
        options:
          - 'patch'
          - 'minor'
          - 'major'
          - 'auto'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle.properties', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Gradle build
        run: ./gradlew build  -x spotlessCheck "-Psemver.scope=${{ github.event.inputs.scope }}" "-Psemver.stage=${{ github.event.inputs.stage }}"

      - name: Stop Gradle daemons
        run: ./gradlew --stop

  generate-tag:
    runs-on: ubuntu-latest

    needs:
      - build

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN_GITHUB_ACTION }}

      - name: Set up Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle.properties', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Generate Tag
        run: ./gradlew createSemverTag "-Psemver.scope=${{ github.event.inputs.scope }}" "-Psemver.stage=${{ github.event.inputs.stage }}"

      - name: Push changes to tag
        run: git push --follow-tags

      - name: Stop Gradle daemons
        run: ./gradlew --stop
